### ISSUE TITLE
Image zoom. reduce please

### ISSUE THREAD

**Issue by danielgeen** [markendley/drjdcrft#1]
Hey mate, 

Smashed this site. So good! 

Can you please make the zoom effect on the large images more subtle? It looks like it zooms in like 30% or something at the moment... 

Can you make it like half of what it is now?

Thanks

**Comment by markendley** [comment]
Sure I slowed it down by 10s
and I decreased the zoom from **1.8 => 1** to just **1.2 => 1**

**Comment by danielgeen** [comment]
Better thanks but can we go even less zoom?

**Comment by danielgeen** [comment]
Also some of the full width images dont seem to have been reduced yet? just the title images...? 

Like on this page... https://demoplatform.net/drjodicroft/gynaecology/
This image zooms heaps... 
<img width="1663" alt="Screenshot 2023-08-27 at 2 49 21 pm" src="https://github.com/markendley/drjdcrft/assets/91818549/07f7be62-1a4d-4104-bb22-f73c427abfec">

**Comment by markendley** [comment]
oh that's a different module... fixed.
