### ISSUE TITLE
please make a video field also 

### ISSUE THREAD

**Issue by danielgeen** [markendley/drjdcrft#4]
Hey make on this page... https://demoplatform.net/drjodicroft/gynaecology/

Can you please make this image field also able to be a looping video?
<img width="1684" alt="Screenshot 2023-08-25 at 3 28 58 pm" src="https://github.com/markendley/drjdcrft/assets/91818549/40ef7123-f6aa-4fb9-a9d4-84c80328b9d2">

**Comment by markendley** [comment]
done

**Comment by danielgeen** [comment]
Thanks mate. The video seems fairly zoomed in? Any way to make it fit the circle better?

**Comment by markendley** [comment]
ok, better now?

**Comment by danielgeen** [comment]
Yep perfect. You nailed this site mate! Well done
